export const basePermissionList = [
    {
        level_name: "Roles & Permissions",
        input_name: "roles_permissions",
        value: ["is_view", "is_add", "is_edit", "is_delete"],
        is_view: false,
        is_add: false,
        is_edit: false,
        is_delete: false,
    },
    {
        level_name: "User Management",
        input_name: "user_management",
        value: ["is_view", "is_add", "is_edit", "is_delete"],
        is_view: false,
        is_add: false,
        is_edit: false,
        is_delete: false,
    },
    {
        level_name: "Project Management",
        input_name: "project_management",
        value: ["is_view", "is_add", "is_edit", "is_delete"],
        is_view: false,
        is_add: false,
        is_edit: false,
        is_delete: false,
    },
    {
        level_name: "Task Management",
        input_name: "task_management",
        value: ["is_view", "is_add", "is_edit", "is_delete"],
        is_view: false,
        is_add: false,
        is_edit: false,
        is_delete: false,
    },
    {
        level_name: "Calendar Management",
        input_name: "calendar_management",
        value: ["is_view"],
        is_view: false,
        is_add: false,
        is_edit: false,
        is_delete: false,
    },
    {
        level_name: "Document/File Management",
        input_name: "document_file_management",
        value: ["is_view", "is_add", "is_edit", "is_delete"],
        is_view: false,
        is_add: false,
        is_edit: false,
        is_delete: false,
    },
    {
        level_name: "Message/Support Management",
        input_name: "message_support_management",
        value: ["is_view", "is_add"],
        is_view: false,
        is_add: false,
        is_edit: false,
        is_delete: false,
    },
];
